export enum SectionKeyEnum {
	HeroSection = "heroSection",
	AboutSection = "aboutSection",
	ServicesSection = "servicesSection",
	PricingSection = "pricingSection",
	TestimonialsSection = "testimonialsSection",
	GallerySection = "gallerySection",
	MapSection = "mapSection",
	ProductsSection = "productsSection",
	FaqsSection = "faqsSection",
	HowItWorksSection = "howItWorksSection",
	TargetAudienceSection = "targetAudienceSection",
	DemoShowcaseSection = "demoShowcaseSection",
	TrustSection = "trustSection",
	CTASection = "ctaSection",
	PromoLiveBanner = "promoLiveBanner",
}
